### ISSUE TITLE
I found 2 bugs

### ISSUE THREAD

**Issue by giszh86** [apdevelop/tile-map-service-net5#3]
1.RasterTileSource
When I use the tif generated by arcgis, it enters an infinite loop，The problem occurs in the default of line 330, and there is no self-increment of keyIndex, so the loop cannot be escaped
![image](https://user-images.githubusercontent.com/8955999/160530060-e3ca1d53-e24e-43a6-a562-532fabb3f969.png)

2.Also RasterTileSource
If the image has 4 bands, the wms service will be gray and white, no longer a color map
![image](https://user-images.githubusercontent.com/8955999/160530261-ba90e717-3a79-4e3a-ac8f-4f9904e101ef.png)

**Comment by giszh86** [comment]
This my TIF
https://www.123pan.com/s/mJPRVv-B3yyd

**Comment by apdevelop** [comment]
1. There are actually several additional Geographic CS Parameter Keys tags, which are not processed in previous switch cases. Just skipping them is OK, because GeoTIFF support is very limited right now.
2. The GeoTIFF format is rather versatile 😄, needs a lot of test samples. The simple fix can be done in `ReadTiffTile()`:
`var samplesPerPixel = tiff.GetField(TiffTag.SAMPLESPERPIXEL)[0].ToInt();`
`var srcOffset = pixelNumber * samplesPerPixel;`

**Comment by giszh86** [comment]
It is work now, thanks.
